### ISSUE TITLE
Drive link access 

### ISSUE THREAD

**Issue by Aayush204** [simranenggprojects/Indian-Sign-Langauge#1]
Please give the drive link access i need for reference as we are doing project on the same topic

**Comment by simranvolunesia** [comment]
I changed drive settings, thanks a ton for bringing that to notice. Do check now with any id and do let me know 😀

**Comment by Aayush204** [comment]
Ok nice , can you tell me did you create mongdb database from the windows
software available named mongodb compass ?

And if possible please describe the process in short , sorry to bother you

**Comment by simranvolunesia** [comment]
Yeah we did that, you got that right. We used mongodb for login and signup. Its completely ok we all grow by helping each other. 
At that, simply localhost connection was made up and then databases created (you would get to know about databases from code) and then python code did it's work.
Do ask if something is still unclear.

**Comment by Aayush204** [comment]
Thanks, I'll check it out.

**Comment by Aayush204** [comment]
which tensorflow version is recomended for this project ?? after doing all the database part and after signing in when clicked on gesture to speech isl the camera opens and its freezed below is the error shown in the terminal , please take a look and help us 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Lib\site-packages\werkzeug\wsgi.py", line 506, in __next__
    return self._next()
  File "C:\ProgramData\Anaconda3\Lib\site-packages\werkzeug\wrappers\base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "C:\Users\aayus\Downloads\Compressed\Indian-Sign-Langauge-Identifier-main\app.py", line 124, in gen
    img_text = predictor()
  File "C:\Users\aayus\Downloads\Compressed\Indian-Sign-Langauge-Identifier-main\app.py", line 43, in predictor
    result = classifier.predict(test_image)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow\python\keras\engine\training.py", line 130, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow\python\keras\engine\training.py", line 1562, in predict
    version_utils.disallow_legacy_graph('Model', 'predict')
  File "C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow\python\keras\utils\version_utils.py", line 122, in disallow_legacy_graph
    raise ValueError(error_msg)
ValueError: Calling `Model.predict` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.predict` with eager mode enabled.

**Comment by Aayush204** [comment]
The mydata/train_set has images only upto the letter A to I 
after I like folders of letters from J to Z are empty  in the drive link you gave, please give the link or can you please add the missing images 

were these images present while you guys trained your model ?
